version: '3.8'
services:

  cliport:
    image: yang-cliport
    container_name: cliport
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/home/yang/cliport
      - ../:/home/yang/llm # assume it is in the submodule of main repo
      - /export/home/yang/memory/primary_experiment:/home/yang/memory_storage
